### ISSUE TITLE
new UVLReader is too restrict with the syntax raising errors with correct models

### ISSUE THREAD

**Issue by jmhorcas** [flamapy/fm_metamodel#95]
Converting a FeatureIDE (.xml) file to UVL (.uvl) using FeatureIDE and then reading it with the UVLReader of Flama raises some errors related with "\t\t" and "EOF" stuff. Those errors did not happen in the previous version of UVLReader.
I've tried with some models (including the linux one).

**Comment by jmhorcas** [comment]
I think that the new parser does not allow empty lines throught the model.

**Comment by jagalindo** [comment]
NOw the parser is shared between f-ide and flama (and hopefuly others). So you should face the same issues in all the tools
