### ISSUE TITLE
Feature names are not shown for Operations

### ISSUE THREAD

**Issue by coemgen1992** [flamapy/fm_metamodel#97]
I installed the latest pip versions of flamapy for a lecture and tested the provided tutorials.

When executing the following command:

``` flamapy-admin cli use_operation_from_file FMCoreFeatures  pizzas.uvl```

I get: 
```{'result': [<flamapy.metamodels.fm_metamodel.models.feature_model.Feature object at 0x10f03dee0>, <flamapy.metamodels.fm_metamodel.models.feature_model.Feature object at 0x10f03e2a0>, <flamapy.metamodels.fm_metamodel.models.feature_model.Feature object at 0x10f03d190>, <flamapy.metamodels.fm_metamodel.models.feature_model.Feature object at 0x10f03f080>]}```

As the output. Similar results when using other feature name-based commands, such as Products from other plugins.

This may be introduced in an update, as the google collab version is still the older one I guess?

**Comment by jagalindo** [comment]
Dear Kevin, we have just released a new version among new documentation that solve this issue https://docs.flamapy.org/
