### ISSUE TITLE
Error: FMMetrics cannot be instantiated

### ISSUE THREAD

**Issue by jmhorcas** [flamapy/fm_metamodel#98]
The following error raises when using the FMMetrics class:

`Can't instantiate abstract class FMMetrics without…tation for abstract method 'model_type_extension'`

Concretely, I can observe that the FMMetrics class misses the `model_type_extension` definition from its parent class which defines this method as abstract.

**Comment by jagalindo** [comment]
Please note that that operation is not intended to be called manually on metamodel instances but simply the main abstract class using the discovermetamodel class. 

How are you using it?
